//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::microsoft::maker::SecuritySystem;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
IAsyncOperation<SecuritySystemTriggerCaptureResult^>^ SecuritySystemServiceEventAdapter::TriggerCaptureAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemTriggerCaptureCalledEventArgs(info);
    TriggerCaptureCalled(this, args);
    return SecuritySystemTriggerCaptureCalledEventArgs::GetResultAsync(args);
}

// Property Reads
IAsyncOperation<SecuritySystemGetVersionResult^>^ SecuritySystemServiceEventAdapter::GetVersionAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemGetVersionRequestedEventArgs(info);
    GetVersionRequested(this, args);
    return SecuritySystemGetVersionRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<SecuritySystemGetIsEnabledResult^>^ SecuritySystemServiceEventAdapter::GetIsEnabledAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemGetIsEnabledRequestedEventArgs(info);
    GetIsEnabledRequested(this, args);
    return SecuritySystemGetIsEnabledRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<SecuritySystemGetLastCaptureFileNameResult^>^ SecuritySystemServiceEventAdapter::GetLastCaptureFileNameAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemGetLastCaptureFileNameRequestedEventArgs(info);
    GetLastCaptureFileNameRequested(this, args);
    return SecuritySystemGetLastCaptureFileNameRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<SecuritySystemGetLastCaptureTimeResult^>^ SecuritySystemServiceEventAdapter::GetLastCaptureTimeAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemGetLastCaptureTimeRequestedEventArgs(info);
    GetLastCaptureTimeRequested(this, args);
    return SecuritySystemGetLastCaptureTimeRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<SecuritySystemGetLastUploadTimeResult^>^ SecuritySystemServiceEventAdapter::GetLastUploadTimeAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new SecuritySystemGetLastUploadTimeRequestedEventArgs(info);
    GetLastUploadTimeRequested(this, args);
    return SecuritySystemGetLastUploadTimeRequestedEventArgs::GetResultAsync(args);
}

// Property Writes
IAsyncOperation<SecuritySystemSetIsEnabledResult^>^ SecuritySystemServiceEventAdapter::SetIsEnabledAsync(_In_ AllJoynMessageInfo^ info, _In_ bool value)
{
    auto args = ref new SecuritySystemSetIsEnabledRequestedEventArgs(info, value);
    SetIsEnabledRequested(this, args);
    return SecuritySystemSetIsEnabledRequestedEventArgs::GetResultAsync(args);
}

